### PR TITLE
Stamen migration to Stadia Maps (+ add new styles)

### LINKED ISSUE #350: Reflect that Stamen tiles are now hosted by Stadia Maps
See http://maps.stamen.com/stadia-partnership/ and https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/.

This will probably be a semver breaking change regardless of any reorganization (since an API key will be required in the future). Additionally, the approach taken by [Leaflet Providers](https://github.com/leaflet-extras/leaflet-providers/pull/520), [OpenLayers](https://github.com/openlayers/openlayers/issues/14963), etc. has been to change the source name while we're making breaking changes anyways.

I'll try to work up a PR myself and let you know if I get stuck; my R is a bit rusty ;)

### PR DESCRIPTION
**Pull request by ianthetechie**
## Before you open your PR

- [X] Did you run R CMD CHECK?
- [X] Did you run `roxygen2::roxygenise(".")`?

## Description

Reflects that Stamen map tiles are now hosted by Stadia Maps. The old endpoints will start showing warning tiles sometime in September before being shut off on October 31, 2023.

Closes #350.

### CODE REVIEW

**Comment by ianthetechie** [comment]
Just a quick bump on this, as we plan to start brownouts toward the end of September to let people know to switch over. It would be great to have ggmap updated.

**Comment by ianthetechie** [comment]
Bump @dkahle?

**Comment by dkahle** [comment]
This is great, thanks @ianthetechie. Is there a reason why you removed `get_stamenmap()` completely instead of just adding `get_stadiamap()`? I would think it preferable to simply make the latter in addition to the former, `.Deprecated()` it (if that's still relevant at this point, which it appears to be), and when the former stops working `.Defunct()` it and point to `get_stadiamap()`. Thoughts?

**Comment by ianthetechie** [comment]
Good question @dkahle. To be completely honest this is the first time I've written anything in R in like 8 years, so I don't know what the generally accepted practices are around deprecation in the R community. Since it's already a breaking change (API keys are required so that's a semantically breaking change) and the Stamen function would only make sense with a subset of styles, I thought it was easier to just remove it as that's what both OpenLayers and Leaflet Providers opted for, but I'm open to your suggestions on this. Feel free to suggest / make edits directly (I think those are enabled).

**Comment by jimr1603** [comment]
I installed Ian's version to give it a try after finding the brownout in my pipeline.

Works smooth enough once I've got the API key, and the auto messages got me on the right pages to get an API key quickly.

Unfortunately it looks like Stadia is inheriting the brownout at this stage. The following snippet has brownout tiles:

``` 

get_stadiamap(bbox = c(left = -1.56, bottom = 53.78, right = -1.5,top = 53.82),
              zoom = 14) %>%
  ggmap()

```

For backwards-compatibility I'd suggest leaving in `get_stamen` but replacing the function with a message to change to the new function.

**Comment by ianthetechie** [comment]
> Unfortunately it looks like Stadia is inheriting the brownout at this stage. The following snippet has brownout tiles:

@jimr1603 Quick clarification request: did you add an API key? We still allow unauthenticated requests during the brownout, but you will have to invoke `register_stadiamaps("YOUR-API-KEY")` to keep using the tiles after October 31st.

**Comment by jimr1603** [comment]
I did, but I'll see if this still happens after the computer's had a couple
of reboot cycles, later today.

**Comment by jimr1603** [comment]
Tested it just now and can't replicate. Maybe the session needed restarting after loading the API key the first time, maybe I did something wrong 🤷

**Comment by ianthetechie** [comment]
Just a quick bump on this @dkahle. The total shutoff date is this week for the old Stamen URLs.

**Comment by dkahle** [comment]
Got it. Thanks @ianthetechie!

**Pull request merged**
