### PR TITLE
Fixing coord_map() replacement to work with ggplot2 dev version

### PR DESCRIPTION
**Pull request by mvkorpel**
Related to https://github.com/tidyverse/ggplot2/commit/165e4c9bcc102541d9a92de829ce4801b1772fcb. Should fix issue #144 (which should not occur with ggplot2 2.2.1 from CRAN).

### CODE REVIEW

**Comment by brendanhoganvt** [comment]
Bravo!  This worked for me.  I had been torn between my interest in some new development features in ggplot2, and my ggmap needs, so this is a huge help.  Thank you!

**Comment by JJ** [comment]
Although I get a different error, which was not present in the development version
~~~
Error in if (theme$panel.ontop) { : argumento tiene longitud cero
~~~
(meaning 0 length argument)

**Comment by scottmmjackson** [comment]
@JJ could you give a little more reproduction information on the error you got?

I pulled down @mvkorpel's branch and merged it with https://github.com/scottmmjackson/ggmap/tree/sj-add-tests locally. The `ggmap()` test passes but the `ggmapplot()` test fails with the same error:

```
Warnings -----------------------------------------------------------------------
1. ggmapplot example works (@test-ggmap.R#13) - ggmapplot syntax deprecated, use ggmap.

2. ggmapplot example works (@test-ggmap.R#13) - fullpage and expand syntaxes deprecated, use extent.

Failed -------------------------------------------------------------------------
1. Error: ggmapplot example works (@test-ggmap.R#13) ---------------------------
object 'fullpage' not found
1: ggmapplot(map) at /Users/scottmmjackson/ggmap/tests/testthat/test-ggmap.R:13
2: ggmap(ggmap, fullpage = fullpage, base_layer = base_layer, maprange = FALSE, expand = FALSE, 
       ggmapplot = TRUE) at /Users/scottmmjackson/ggmap/R/ggmap.R:606
3: eval(args$fullpage) at /Users/scottmmjackson/ggmap/R/ggmap.R:449
4: eval(expr, envir, enclos)
```

That seems like a separate problem dealing with the use of the `eval(names(args))` trick. I think since in this case, it's being used to handle deprecated arguments, maybe we should name those args as part of the signature and wrap their handler in `if(!missing(fullpage))`, `missing()` is a very stable function that was around in the `S` days, so this guarantees broad compatibility.

**Comment by scottmmjackson** [comment]
@JJ I think I found what you're talking about. It exists in CRAN checking on master:

```
Running examples in ‘ggmap-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: theme_nothing
> ### Title: Make a blank ggplot2 theme.
> ### Aliases: theme_nothing
> 
> ### ** Examples
> 
> 
> 
> # no legend example
> n <- 50
> df <- expand.grid(x = 1:n,y = 1:n)[sample(n^2,.5*n^2),]
> p <- qplot(x, y, data = df, geom = 'tile')
> p
> p + theme_nothing()
Error in if (theme$panel.ontop) { : argument is of length zero
Calls: <Anonymous> ... print.ggplot -> ggplot_gtable -> <Anonymous> -> f -> lapply -> FUN
Execution halted
```

Probably shouldn't block the merge of this PR.

**Comment by JJ** [comment]
@scottmmjackson sorry, it was some time ago and I didn't take a screenshot...

**Comment by scottmmjackson** [comment]
@JJ It's all good, I think I fixed it in #186, if you wanted to pull it down and confirm that'd be great!

**Comment by scottmmjackson** [comment]
I think this is good to go. The examples are still failing due to `theme_nothing` but I think that's a separate issue.

**Pull request merged**
